### ISSUE TITLE
cypher map with integer keys does not work

### ISSUE THREAD

**Issue by transistive** [neo4j-php/Bolt#63]
**Describe the bug**
The case came up when integrating testkit with the driver. Apparently a map in cypher can have integer keys. I currently cannot find a way to do it without producing a read error. (my best guess would be to use a stdClass object with integer variable names)

**To Reproduce**
```php
// standard bolt creation logic ...

$stdClass = new stdClass();
$val = 0;
$stdClass->$val = 'x';
$val = 1;
$stdClass->$val = 'y';
$bolt->run('RETURN $x AS x', ['x' => $stdClass]);
```

**Expected behavior**
That it returns a map or object of the form: {0: 'x', 1: 'y'}

**Desktop (please complete the following information):**
 - OS: [Linux box 5.14.10-1-MANJARO #1 
 - PHP Version: 8.0.11
 - Neo4j Version: 4.3.6
 - Bolt Library Version: master

**Additional context**

**Comment by stefanak-michal** [comment]
I'm looking of packer and the query is well formed. A explanation for you. It's hard to say why there is Read error when receiving response from server. If I try it with array (list) it works.

```php
$neo->run('RETURN $x AS x', ['x' => (object)['dog', 'and', 'cat']]);
```

is packed as:
```
> 00 25 b3 10    8e 52 45 54    55 52 4e 20    24 78 20 41    53 20 78 a1    81 78 a3 00    83 64 6f 67    01 83 61 6e    64 02 83 63    61 74 a0
```

00 25 - size of message is correct. DEC is 37 and message has 37 hex values

b3 10 - structure with RUN signature, correct

8e 52 45 54    55 52 4e 20    24 78 20 41    53 20 78 - query as string, correct

a1 - marker for map with parameter, only one parameter. correct

81 78 - string with length 1. Contains parameter key "x". correct

a3 - parameter value is map with 3 entries. correct.

00    83 64 6f 67 - first is key 0. correct. string with 3 hex values. correct. (0 - dog)

01 83 61 6e    64 - first is key 1. correct. string with 3 hex values. correct. (1 - and)

02 83 63    61 74 - first is key 2. correct. string with 3 hex values. correct. (2 - cat)

a0 - empty map at the end, because of extra query parameters. correct.

**Comment by stefanak-michal** [comment]
I think it can be related to Neo4j. Because if you open up neo4j browser and try to set up parameter
```
:param x => ({ 0:'dog', 1:'and', 2:'cat' })
```

You will get

```
Syntax Error
Invalid input '(': expected "+" or "-" (line 1, column 8 (offset: 7))
"RETURN ({ 0:'dog', 1:'and', 2:'cat' })"
        ^
```

But if you try with string keys:

```
:param x => ({ zero:'dog', one:'and', two:'cat' })
```

it works.

Propably dictionary can't have keys starting with number.

**Comment by stefanak-michal** [comment]
fa468e2

**Comment by transistive** [comment]
Hmm, very interesting! I wonder why testkit has tests for that exact use case 🤔

Maybe they expect the driver to translate the integers to strings. I will double check with the neo4j team.

Thanks for the help!

-------- Original Message --------

**Comment by stefanak-michal** [comment]
https://github.com/neo4j-php/Bolt/releases/tag/v2.5.3

**Comment by transistive** [comment]
Thanks for the quick update!
